# Generated by Django 4.1.2 on 2023-02-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_rename_pic4_buyer_pic_buyer_addressline2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='addressline4',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='addressline2',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='addressline3',
            field=models.CharField(default='', max_length=150),
        ),
    ]
