# Generated by Django 4.1.2 on 2023-02-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='name',
            new_name='product',
        ),
    ]
