# Generated by Django 4.1.2 on 2023-02-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_checkoutproduct_qty_checkoutproduct_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutproduct',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='checkoutproduct',
            name='total',
        ),
    ]
