# Generated by Django 4.1.2 on 2023-02-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_remove_checkoutproduct_qty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckoutProduct',
        ),
    ]
