# Generated by Django 4.1.2 on 2023-02-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_delete_checkoutproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
