# Generated by Django 4.1.2 on 2023-02-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_remove_checkoutproduct_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutproduct',
            old_name='Checkout',
            new_name='checkout',
        ),
    ]
